version: "3"

services:
  db:
    image: postgres
    container_name: db
    env_file: .env
    restart: always
    init: true
    ports:
      - "5432:5432"
      - "5433:5433"
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    build: backend
    env_file: backend/.env
    container_name: backend
    hostname: backend
    restart: always
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - db

  frontend:
    build: frontend
    env_file: frontend/.env
    container_name: frontend
    hostname: frontend
    restart: always
    init: true
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - backend

volumes:
  postgres:

networks:
  todos:
    name: todos
    driver: bridge
